mysite/blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'
urlpatterns = [
    # /blog/
    path('', views.PostLV.as_view(), name='index'),

    # /blog/post
    path('post/', views.PostLV.as_view(), name='post_list'),

    # /blog/post/django-example(slug)
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # /blog/archive
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # /blog/archive/[year]
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # /blog/archive/[year]/[month]/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # /blog/archive/[year]/[month]/[day]
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # /blog/archive/today
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # /blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),

    # 생성, 변경, 수정, 삭제
    # /blog/add/
    path('add/', views.PostCreateView.as_view(), name='add'),
    # /blog/change/
    path('change/', views.PostChangeLV.as_view(), name='change'),
    # /blog/99/update/
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    # /blog/99/delete/
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

mysite/bookmark/urls.py
from django.urls import path
# from .views import BookmarkLV, BookmarkDV
from . import views

app_name = 'bookmark'

urlpatterns = [
    
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),

    # 생성, 변경, 수전 , 삭제기능을 위한 URL
    # /bookmark/add/
    path('add/', views.BookmarkCreateView.as_view(), name='add'),
    # /bookmark/change/
    path('change/', views.BookmarkChangeLV.as_view(), name='change'),
    # /bookmark/99/update/
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update'),
    # /bookmark/99/delete/
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # 인증 URL 3개 추가
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', views.UserCreateDoneTV.as_view(), name='register_done'),
    
    # home(main page)
    path('', views.HomeView.as_view(), name = 'home'),
    # bookmark urls.py 
    path('bookmark/', include('bookmark.urls')), 
    # blog urls.py
    path('blog/', include('blog.urls')),
    # photo urls.py
    path('photo/', include('photo.urls')),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/photo/urls.py
from django.urls import path
from . import views

app_name = 'photo'
urlpatterns = [
    # /photo/
    path('', views.AlbumLV.as_view(), name = 'index'),
    # /photo/album/  -> 참조 함수는 위와 같다.
    path('album/', views.AlbumLV.as_view(), name='album_list'),

    # /photo/album/99/
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),

    # /photo/photo/99/
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    # create/update/delete url
    # /photo/album/add/
    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),
    # /photo/album/change/
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),
    # /photo/album/99/update/
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),
    # /photo/album/99/delete/
    path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),
    
    # /photo/photo/add/
    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),
    # /photo/photo/change/
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),
    # /photo/photo/99/update/
    path('photo/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),
    # /photo/photo/99/delete/
    path('photo/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),
]

mysite/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Django Blog Homepage{% endblock %}</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <!-- 다른 html 파일에서 style을 재정의 할 수도 있으므로 block처리 한다. 여기서는 tag이름을 extra-style로 정의한다. -->
    {% block extra-style %}{% endblock %}
</head>
<body style="padding-top:90px;">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg bg-primary fixed-top">
        <div class="container-fluid">
          <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic" >Blog</span>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Bookmark</a>
              </li>
              <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'blog:index' %}">Blog</a>
              </li>
              <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'photo:index' %}">Photo</a>
              </li>
              <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Util
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a></li>
                  <li><a class="dropdown-item" href="{% url 'blog:search' %}">Search</a></li>
                </ul>
              </li>
              
              <!-- main 메뉴창에서 Add 추가 -->
              <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Add</a>
                <!-- <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Add</a> -->
                <ul class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'bookmark:add' %}">Bookmark</a>
                  <a class="dropdown-item" href="{% url 'blog:add' %}">Post</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a>
                  <a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a>
                </ul>
              </li>
              
              <!-- main 메뉴창에서 change 추가 -->
              <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Change</a>
                <!-- <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Add</a> -->
                <ul class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'bookmark:change' %}">Bookmark</a>
                  <a class="dropdown-item" href="{% url 'blog:change' %}">Post</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'photo:album_change' %}">Album</a>
                  <a class="dropdown-item" href="{% url 'photo:photo_change' %}">Photo</a>
                </ul>
              </li>

            </ul>
            <!-- 오른쪽 끝 검색창 생성 -->
            <form class="form-inline my-2" action="" method="post">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
            </form>

          <li class="nav-item dropdown mx-1 btn btn-primary">
            {% if user.is_active %}
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                  <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                </ul>
            {% else %}
            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fas fa-user"></i>&ensp;Anonymous&ensp;
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
              <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
            </ul>
          </li>       
            
          {% endif %}

        </div>
      </nav>
      
      <!-- CONTENT 영역 -->
      <div class="container">
        <!-- container 내용이 달라질 수 있으므로 block 처리 한다. -->
        {% block content %}{% endblock %}
      </div>

      <!-- FOOTER 영억 -->
      <!-- <footer class="fixed-bottom bg-info"> -->
      {% block footer %}{% endblock %}
      <!-- </footer> -->

      <script src="https://kit.fontawesome.com/c998a172fe.js"></script>

      {% block extra-script %}{% endblock %}
</body>
</html>

mysite/templates/home.html
<!-- base.html에서 만든 block들을 overriding 한다. -->

{% extends 'base.html' %}

{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image{
    background-image: url("{% static 'img/lion.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    padding: 20px 0 0 20px;
}
.title{
    color: white;
    font-weight: bold;
}
.powered{
    position: relative;
    top: 77%;
    color: white;
    font-style: italic;
}
</style>
{% endblock %}

{% block content %}
    <div class="home-image">
        <h2 class="title">Django - Python Web Programmming</h2>
        <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap. </h4>
    </div>

    <!-- 선분 긋기 -->
    <hr style="margin: 1px 0;">

    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Bookmark App</h3>
            <p>Bookmark is a Uniform Resource Identifier (URI)
                that is stored for later retrieval in any of varous storage formats.
                You can store your own bookmarks by Bookmark appication.
                It's also possible to update or delete your bookmarks.
            </p>
        </div>
        <div class="col-sm-6">
            <h3>Blog App</h3>
            <p>This application makes it possible to log daily events or write your own interests
                such as hobbies, techniques, etc.
                A typical blg combines text, digital images, and links to other blogs, web pages, and other media related to its topic.
            </p>
        </div>
    </div>
{% endblock content%}

{% block footer %}
<footer class="fixed-bottom bg-info">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; 2022 DjangoBook by A-sy-coding</div>
</footer>
{% endblock %}